"""

Revision ID: 10fa7cdddd13
Revises: d9583b7806ee
Create Date: 2025-07-09 17:23:13.161999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10fa7cdddd13'
down_revision: Union[str, None] = 'd9583b7806ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AIQuestion', sa.Column('picture', sa.String(), nullable=True))
    op.add_column('Question', sa.Column('picture', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Question', 'picture')
    op.drop_column('AIQuestion', 'picture')
    # ### end Alembic commands ###
