"""Add author to question

Revision ID: 129e29a03479
Revises: 31e0fd872f11
Create Date: 2025-06-07 20:04:47.484015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '129e29a03479'
down_revision: Union[str, None] = '31e0fd872f11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq__AIQuestion__id'), 'AIQuestion', ['id'])
    op.add_column('Question', sa.Column('author_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix__Question__author_id'), 'Question', ['author_id'], unique=False)
    op.create_unique_constraint(op.f('uq__Question__id'), 'Question', ['id'])
    op.create_foreign_key(op.f('fk__Question__author_id__Users'), 'Question', 'Users', ['author_id'], ['id'])
    op.create_unique_constraint(op.f('uq__Settings__id'), 'Settings', ['id'])
    op.create_unique_constraint(op.f('uq__Users__id'), 'Users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq__Users__id'), 'Users', type_='unique')
    op.drop_constraint(op.f('uq__Settings__id'), 'Settings', type_='unique')
    op.drop_constraint(op.f('fk__Question__author_id__Users'), 'Question', type_='foreignkey')
    op.drop_constraint(op.f('uq__Question__id'), 'Question', type_='unique')
    op.drop_index(op.f('ix__Question__author_id'), table_name='Question')
    op.drop_column('Question', 'author_id')
    op.drop_constraint(op.f('uq__AIQuestion__id'), 'AIQuestion', type_='unique')
    # ### end Alembic commands ###
