"""Add answer model, remove answers lists in question

Revision ID: 12d2ca126a77
Revises: 129e29a03479
Create Date: 2025-06-07 21:21:05.586804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12d2ca126a77'
down_revision: Union[str, None] = '129e29a03479'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('question_id', sa.UUID(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['Question.id'], name=op.f('fk__Answers__question_id__Question')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__Answers')),
    sa.UniqueConstraint('id', name=op.f('uq__Answers__id'))
    )
    op.create_index(op.f('ix__Answers__question_id'), 'Answers', ['question_id'], unique=False)
    op.drop_column('Question', 'answers')
    op.drop_column('Question', 'right_answers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Question', sa.Column('right_answers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('Question', sa.Column('answers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix__Answers__question_id'), table_name='Answers')
    op.drop_table('Answers')
    # ### end Alembic commands ###
