"""Add explanation to question

Revision ID: 1a940c72dbb9
Revises: f03e34094c73
Create Date: 2025-06-09 23:58:09.188069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a940c72dbb9'
down_revision: Union[str, None] = 'f03e34094c73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq__Chapter__id'), 'Chapter', ['id'])
    op.add_column('Question', sa.Column('explanation', sa.String(), nullable=True))
    op.create_unique_constraint(op.f('uq__Topic__id'), 'Topic', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq__Topic__id'), 'Topic', type_='unique')
    op.drop_column('Question', 'explanation')
    op.drop_constraint(op.f('uq__Chapter__id'), 'Chapter', type_='unique')
    # ### end Alembic commands ###
