"""add author and explanation to aiquestion

Revision ID: d9583b7806ee
Revises: 1a940c72dbb9
Create Date: 2025-06-11 20:14:05.215950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9583b7806ee'
down_revision: Union[str, None] = '1a940c72dbb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AIQuestion', sa.Column('author_id', sa.UUID(), nullable=True))
    op.add_column('AIQuestion', sa.Column('explanation', sa.String(), nullable=True))
    op.create_index(op.f('ix__AIQuestion__author_id'), 'AIQuestion', ['author_id'], unique=False)
    op.create_foreign_key(op.f('fk__AIQuestion__author_id__Users'), 'AIQuestion', 'Users', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk__AIQuestion__author_id__Users'), 'AIQuestion', type_='foreignkey')
    op.drop_index(op.f('ix__AIQuestion__author_id'), table_name='AIQuestion')
    op.drop_column('AIQuestion', 'explanation')
    op.drop_column('AIQuestion', 'author_id')
    # ### end Alembic commands ###
