"""Add chapter and topic

Revision ID: f03e34094c73
Revises: 12d2ca126a77
Create Date: 2025-06-08 00:45:55.268562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f03e34094c73'
down_revision: Union[str, None] = '12d2ca126a77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Chapter',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__Chapter')),
    sa.UniqueConstraint('id', name=op.f('uq__Chapter__id'))
    )
    op.create_table('Topic',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chapter_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['Chapter.id'], name=op.f('fk__Topic__chapter_id__Chapter')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__Topic')),
    sa.UniqueConstraint('id', name=op.f('uq__Topic__id'))
    )
    op.create_index(op.f('ix__Topic__chapter_id'), 'Topic', ['chapter_id'], unique=False)
    op.add_column('AIQuestion', sa.Column('topic_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix__AIQuestion__topic_id'), 'AIQuestion', ['topic_id'], unique=False)
    op.create_foreign_key(op.f('fk__AIQuestion__topic_id__Topic'), 'AIQuestion', 'Topic', ['topic_id'], ['id'])
    op.create_unique_constraint(op.f('uq__Answers__id'), 'Answers', ['id'])
    op.add_column('Question', sa.Column('topic_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix__Question__topic_id'), 'Question', ['topic_id'], unique=False)
    op.create_foreign_key(op.f('fk__Question__topic_id__Topic'), 'Question', 'Topic', ['topic_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk__Question__topic_id__Topic'), 'Question', type_='foreignkey')
    op.drop_index(op.f('ix__Question__topic_id'), table_name='Question')
    op.drop_column('Question', 'topic_id')
    op.drop_constraint(op.f('uq__Answers__id'), 'Answers', type_='unique')
    op.drop_constraint(op.f('fk__AIQuestion__topic_id__Topic'), 'AIQuestion', type_='foreignkey')
    op.drop_index(op.f('ix__AIQuestion__topic_id'), table_name='AIQuestion')
    op.drop_column('AIQuestion', 'topic_id')
    op.drop_index(op.f('ix__Topic__chapter_id'), table_name='Topic')
    op.drop_table('Topic')
    op.drop_table('Chapter')
    # ### end Alembic commands ###
